export default function handler(req, res) {
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Cache-Control', 's-maxage=86400, stale-while-revalidate');
  if (req.method === 'OPTIONS') { res.status(200).end(); return; }
  const { pathology, category, society } = req.query;
  let data = [...RECS];
  if (pathology && pathology !== 'Toutes') data = data.filter(r => r.pathology === pathology);
  if (category && category !== 'Toutes') data = data.filter(r => r.category === category);
  if (society && society !== 'Toutes') data = data.filter(r => r.society === society);
  data.sort((a, b) => new Date(b.publicationDate) - new Date(a.publicationDate));
  res.status(200).json({ count: data.length, lastUpdated: new Date().toISOString(), data });
}

const RECS = [
  { id:"eular-jak-safety-2025", society:"EULAR", societyColor:"#d4a017", title:"Sécurité des inhibiteurs de JAK", pathology:"Polyarthrite rhumatoïde", category:"Sécurité", publicationDate:"2025-03-10", updatedAt:"2025-03-10", url:"https://ard.bmj.com", summary:"Point de position EULAR sur la sécurité CV et néoplasique des JAKi (ORAL Surveillance). Stratification du risque.", keyPoints:["Éviter JAKi chez > 65 ans, fumeurs ou risque CV élevé","Préférer abatacept ou rituximab dans ces profils","Surveillance CV et bilan lipidique","Dépistage cancers cutanés au long cours","Réévaluation bénéfice/risque annuelle"], quiz:[{type:"tf",q:"Les JAKi sont déconseillés chez les > 65 ans avec facteurs de risque CV.",answer:true,expl:"EULAR recommande d'éviter les JAKi dans ce profil, en privilégiant abatacept ou rituximab."},{type:"mcq",q:"Quel essai a conduit à la réévaluation des JAKi ?",options:["MONARCH","ORAL Surveillance","EMPIRE","BREVACTA"],answer:1,expl:"L'essai ORAL Surveillance a mis en évidence un surrisque CV et cancéreux sous tofacitinib vs anti-TNF."}]},
  { id:"eular-cvd-rheum-2024", society:"EULAR", societyColor:"#d4a017", title:"Risque cardiovasculaire dans les rhumatismes inflammatoires", pathology:"Transversal", category:"Comorbidités", publicationDate:"2024-12-01", updatedAt:"2024-12-01", url:"https://ard.bmj.com", summary:"Mise à jour 2024 EULAR sur le risque CV dans la PR, lupus et SpA. SCORE2, statines, contrôle de l'inflammation.", keyPoints:["Évaluation CV tous les 5 ans (SCORE2)","Multiplicateur × 1,5 pour PR et lupus","Statines si risque CV modéré à élevé","Contrôle de l'activité inflammatoire prioritaire","Éviction tabac, activité physique"], quiz:[{type:"mcq",q:"Quel coefficient multiplicateur EULAR recommande pour la PR ?",options:["× 1,0","× 1,5","× 2,0","× 3,0"],answer:1,expl:"EULAR recommande × 1,5 pour la PR et le lupus appliqué au SCORE2."}]},
  { id:"eular-pregnancy-2024", society:"EULAR", societyColor:"#d4a017", title:"Grossesse dans les rhumatismes inflammatoires", pathology:"Transversal", category:"Situations particulières", publicationDate:"2024-10-01", updatedAt:"2024-10-01", url:"https://ard.bmj.com", summary:"Sécurité des biothérapies pendant la grossesse, SAPL obstétrical, planification préconceptionnelle.", keyPoints:["HCQ compatible grossesse et allaitement","Anti-TNF : arrêt T3 sauf certolizumab","Rituximab contre-indiqué pendant la grossesse","Aspirine + HBPM dans le SAPL obstétrical","Planification préconceptionnelle systématique"], quiz:[{type:"tf",q:"Le certolizumab peut être maintenu tout au long de la grossesse.",answer:true,expl:"Pas de transfert placentaire actif significatif — peut être maintenu si nécessaire."}]},
  { id:"acr-psa-2024", society:"ACR", societyColor:"#1a5fa8", title:"Rhumatisme psoriasique — ACR 2024", pathology:"Rhumatisme psoriasique", category:"Traitement", publicationDate:"2024-11-15", updatedAt:"2024-11-15", url:"https://www.rheumatology.org", summary:"Algorithme ACR 2024 intégrant biothérapies selon manifestations : articulaire, cutanée, enthèse, rachis.", keyPoints:["Anti-TNF en première biothérapie articulaire","Anti-IL-17 si atteinte cutanée prédominante","Anti-IL-23 (guselkumab, risankizumab) articulaire et cutané","Apremilast pour formes légères à modérées","Évaluation enthèses et dactylites"], quiz:[{type:"mcq",q:"En cas d'atteinte cutanée prédominante dans le PsA, quelle classe ?",options:["Anti-TNF","Anti-IL-17","Méthotrexate","JAKi"],answer:1,expl:"Anti-IL-17 privilégiés pour leur efficacité supérieure sur le psoriasis cutané."}]},
  { id:"eular-sjogren-2024", society:"EULAR", societyColor:"#d4a017", title:"Syndrome de Sjögren primitif — EULAR 2024", pathology:"Sjögren", category:"Traitement", publicationDate:"2024-09-01", updatedAt:"2024-09-01", url:"https://ard.bmj.com", summary:"Premières recommandations EULAR : gestion glandulaire, manifestations systémiques, dépistage lymphome.", keyPoints:["Pilocarpine ou céviméline pour la sécheresse","HCQ pour manifestations systémiques légères","Rituximab pour formes systémiques sévères","Dépistage lymphome tous les 1 à 2 ans","ESSDAI systématique"], quiz:[{type:"tf",q:"Le rituximab est recommandé dans les formes systémiques sévères du Sjögren.",answer:true,expl:"EULAR 2024 recommande le rituximab pour les manifestations sévères réfractaires."}]},
